import { StyleSheet } from 'react-native';

import { NUMERIC_DISPLAY_FONT } from '@/theme/fonts';
import type { AppTheme } from '@/theme/theme';

/**
 * マップ画面・ダッシュボード・位置情報表示・メニュー・写真マーカー・GPS権限関連のスタイルを生成する。
 *
 * @param theme - アプリテーマ。
 */
export function createMapStyles(theme: AppTheme) {
  const { colors } = theme;
  const mapPanelBackground = 'rgba(51, 51, 51, 0.80)';
  const mapPanelText = '#ffffff';

  return {
    // Map container / layout
    container: {
      backgroundColor: colors.background,
      flex: 1,
    },
    map: {
      ...StyleSheet.absoluteFill,
    },
    topBar: {
      alignItems: 'flex-start',
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingLeft: 0,
      paddingRight: 16,
      paddingTop: 8,
      zIndex: 2,
    },
    bottomBar: {
      alignItems: 'center',
      bottom: 26,
      flexDirection: 'row',
      gap: 12,
      justifyContent: 'space-between',
      left: 16,
      position: 'absolute',
      right: 16,
      zIndex: 2,
    },
    bottomDashboard: {
      bottom: 20,
      left: 8,
      position: 'absolute',
      right: 8,
      zIndex: 2,
    },
    bottomSideSpacer: {
      width: 50,
    },
    rightControls: {
      flexDirection: 'row',
      gap: 10,
    },

    // Recenter button
    recenterButton: {
      alignItems: 'center',
      backgroundColor: mapPanelBackground,
      borderRadius: 10,
      height: 52,
      justifyContent: 'center',
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.24,
      shadowRadius: 10,
      width: 52,
    },
    recenterButtonContainer: {
      alignItems: 'flex-end',
      height: 52,
      position: 'absolute',
      right: 0,
      top: -60,
      zIndex: 4,
    },
    recenterButtonText: {
      color: '#ffffff',
      fontSize: 13,
      fontWeight: '900',
    },

    // Menu (hamburger / overflow menu)
    menuButton: {
      alignItems: 'center',
      backgroundColor: mapPanelBackground,
      borderBottomLeftRadius: 42,
      borderBottomRightRadius: 14,
      borderTopLeftRadius: 14,
      borderTopRightRadius: 14,
      gap: 6,
      height: 88,
      justifyContent: 'center',
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.24,
      shadowRadius: 10,
      width: 104,
    },
    menuButtonText: {
      color: '#ffffff',
      fontSize: 14,
      fontWeight: '900',
    },
    menuCard: {
      backgroundColor: colors.cardStrong,
      borderColor: colors.border,
      borderRadius: 26,
      borderWidth: 1,
      overflow: 'hidden',
      position: 'absolute',
      right: 16,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 18 },
      shadowOpacity: 0.2,
      shadowRadius: 28,
      top: 104,
      width: 248,
      zIndex: 3,
    },
    menuScrim: {
      ...StyleSheet.absoluteFill,
      backgroundColor: theme.name === 'dark' ? 'rgba(0, 0, 0, 0.5)' : 'rgba(45, 36, 22, 0.24)',
      zIndex: 1,
    },
    menuScrimPressable: {
      flex: 1,
    },
    menuItem: {
      alignItems: 'center',
      borderBottomColor: colors.border,
      borderBottomWidth: 1,
      flexDirection: 'row',
      gap: 14,
      paddingHorizontal: 20,
      paddingVertical: 18,
    },
    menuItemText: {
      color: colors.text,
      fontSize: 17,
      fontWeight: '900',
    },

    // Map display panel (map type / photo layer)
    mapDisplayPanel: {
      backgroundColor: mapPanelBackground,
      borderColor: 'rgba(255, 255, 255, 0.42)',
      borderRadius: 10,
      borderWidth: 1,
      bottom: 72,
      gap: 10,
      padding: 10,
      position: 'absolute',
      right: 0,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.28,
      shadowRadius: 14,
      width: 274,
      zIndex: 10,
    },
    mapDisplayPanelScrim: {
      ...StyleSheet.absoluteFill,
      backgroundColor: 'rgba(0, 0, 0, 0.32)',
      zIndex: 1,
    },
    mapDisplayPhotoDescription: {
      color: 'rgba(255, 255, 255, 0.86)',
      fontSize: 11,
    },
    mapDisplayPhotoRow: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 8,
      justifyContent: 'space-between',
    },
    mapDisplayPhotoTextColumn: {
      flex: 1,
      gap: 3,
    },
    mapDisplayPhotoTitle: {
      color: '#ffffff',
      fontSize: 17,
      fontWeight: '900',
    },
    mapDisplayTypeButton: {
      alignItems: 'center',
      borderColor: 'rgba(255, 255, 255, 0.22)',
      borderRadius: 8,
      borderWidth: 1,
      flex: 1,
      gap: 3,
      justifyContent: 'center',
      minHeight: 106,
      padding: 8,
    },
    mapDisplayTypeButtonSelected: {
      borderColor: '#ffffff',
      borderWidth: 2,
    },
    mapDisplayTypeLabel: {
      color: '#ffffff',
      fontSize: 17,
      fontWeight: '800',
    },
    mapDisplayTypeRow: {
      flexDirection: 'row',
      gap: 8,
    },
    mapDisplayTypeSelectedBadge: {
      backgroundColor: '#138f68',
      borderColor: '#ffffff',
      borderRadius: 999,
      borderWidth: 1,
      paddingHorizontal: 9,
      paddingVertical: 2,
    },
    mapDisplayTypeSelectedBadgeText: {
      color: '#ffffff',
      fontSize: 11,
      fontWeight: '900',
      lineHeight: 14,
    },

    // Location status panel (map overlay showing current location name + movement)
    locationDivider: {
      backgroundColor: 'rgba(255, 255, 255, 0.7)',
      height: 1,
      marginRight: 50,
    },
    locationFadeSegment: {
      flex: 1,
    },
    locationMetaLabel: {
      color: colors.mutedText,
      fontSize: 12,
      fontWeight: '800',
    },
    locationMetaRow: {
      alignItems: 'baseline',
      flexDirection: 'row',
      gap: 3,
    },
    locationMetaValue: {
      color: colors.mutedText,
      fontFamily: NUMERIC_DISPLAY_FONT,
      fontSize: 14,
      letterSpacing: 1,
    },
    locationMovementText: {
      color: '#ffffff',
      fontSize: 17,
      fontWeight: '700',
      paddingLeft: 32,
      paddingRight: 78,
      paddingTop: 5,
    },
    locationName: {
      color: colors.text,
      fontSize: 15,
      fontWeight: '900',
    },
    locationPanelBackground: {
      ...StyleSheet.absoluteFill,
      flexDirection: 'row',
    },
    locationPanelFade: {
      flexDirection: 'row',
      width: 112,
    },
    locationPanelSolid: {
      backgroundColor: mapPanelBackground,
      flex: 1,
    },
    locationPill: {
      alignItems: 'center',
      backgroundColor: colors.surfaceOverlay,
      borderColor: colors.border,
      borderRadius: 999,
      borderWidth: 1,
      flex: 1,
      gap: 2,
      maxWidth: 260,
      paddingHorizontal: 18,
      paddingVertical: 10,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.12,
      shadowRadius: 18,
    },
    locationPrimaryText: {
      color: '#ffffff',
      flexShrink: 1,
      fontSize: 34,
      fontWeight: '900',
      letterSpacing: -1.2,
      lineHeight: 40,
    },
    locationSecondaryText: {
      color: '#ffffff',
      flexShrink: 2,
      fontSize: 18,
      fontWeight: '900',
      letterSpacing: -0.4,
      lineHeight: 24,
      marginBottom: 4,
      marginLeft: 2,
    },
    locationStatusPanel: {
      backgroundColor: 'transparent',
      flex: 1,
      marginRight: 12,
      maxWidth: 280,
      minHeight: 86,
      overflow: 'hidden',
      paddingTop: 10,
    },
    locationTitleRow: {
      alignItems: 'flex-end',
      flexDirection: 'row',
      paddingLeft: 32,
      paddingRight: 78,
    },

    // Bottom dashboard (nav panel)
    dashboardAction: {
      alignItems: 'center',
      height: 50,
      justifyContent: 'center',
      minWidth: 44,
    },
    dashboardActionsRow: {
      flexDirection: 'row',
      gap: 8,
      marginLeft: 110,
      marginRight: 3,
      zIndex: 2,
    },
    dashboardDistanceMetric: {
      alignItems: 'stretch',
      gap: 1,
      justifyContent: 'center',
    },
    dashboardDistanceUnit: {
      color: mapPanelText,
      fontSize: 7,
      fontWeight: '800',
      marginBottom: 3,
      marginLeft: 1,
    },
    dashboardDistanceValueDecimal: {
      color: mapPanelText,
      fontFamily: NUMERIC_DISPLAY_FONT,
      fontSize: 6,
      lineHeight: 10,
    },
    dashboardDistanceValueDot: {
      color: mapPanelText,
      fontFamily: NUMERIC_DISPLAY_FONT,
      fontSize: 11,
      lineHeight: 16,
    },
    dashboardDistanceValueInteger: {
      color: mapPanelText,
      fontFamily: NUMERIC_DISPLAY_FONT,
      fontSize: 11,
      lineHeight: 16,
    },
    dashboardMapButton: {
      alignItems: 'center',
      backgroundColor: mapPanelBackground,
      borderRadius: 10,
      height: 54,
      justifyContent: 'center',
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.24,
      shadowRadius: 7,
      width: 54,
    },
    dashboardMeterBackground: {
      height: 104,
      left: 0,
      position: 'absolute',
      right: 0,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.24,
      shadowRadius: 7,
      top: 0,
    },
    dashboardMeterCluster: {
      height: 56,
      position: 'relative',
      zIndex: 1,
    },
    dashboardMetricLabel: {
      color: mapPanelText,
      fontSize: 11,
      fontWeight: '900',
    },
    dashboardNavPanel: {
      alignItems: 'center',
      backgroundColor: mapPanelBackground,
      borderRadius: 10,
      flex: 1,
      flexDirection: 'row',
      justifyContent: 'space-around',
      minHeight: 54,
      paddingHorizontal: 8,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.24,
      shadowRadius: 7,
    },
    dashboardOdometerMetric: {
      flex: 1.42,
      minWidth: 92,
    },
    dashboardPlaceMetric: {
      borderLeftColor: 'rgba(255, 255, 255, 0.72)',
      borderLeftWidth: 1,
      flex: 1.08,
      justifyContent: 'center',
      minWidth: 76,
      paddingLeft: 7,
    },
    dashboardPlacePrimary: {
      color: mapPanelText,
      fontSize: 13,
      fontWeight: '700',
      lineHeight: 16,
    },
    dashboardPlaceSecondary: {
      color: mapPanelText,
      fontSize: 10,
      fontWeight: '400',
      lineHeight: 13,
    },
    dashboardSummaryPanel: {
      alignItems: 'stretch',
      flexDirection: 'row',
      gap: 6,
      height: 52,
      left: 0,
      paddingLeft: 102,
      paddingRight: 7,
      paddingVertical: 6,
      position: 'absolute',
      right: 0,
      top: 0,
    },
    dashboardTodayMetric: {
      flex: 0.88,
      minWidth: 56,
    },

    // Speedometer panel
    speedDashboardArcSvg: {
      height: 104,
      position: 'absolute',
      width: 104,
    },
    speedDashboardDial: {
      alignItems: 'center',
      height: 104,
      justifyContent: 'center',
      left: 2,
      position: 'absolute',
      top: 0,
      width: 104,
      zIndex: 1,
    },
    speedDashboardDialContent: {
      alignItems: 'center',
      borderRadius: 999,
      height: 84,
      justifyContent: 'center',
      width: 84,
    },
    speedDashboardRingBase: {
      borderColor: '#080808',
      borderRadius: 999,
      borderWidth: 7,
      height: 100,
      position: 'absolute',
      width: 100,
    },
    speedDashboardSpeedUnit: {
      color: mapPanelText,
      fontSize: 13,
      marginTop: -5,
    },
    speedDashboardSpeedValue: {
      fontFamily: NUMERIC_DISPLAY_FONT,
      fontSize: 30,
      lineHeight: 36,
    },
    speedometerDistanceRow: {
      alignItems: 'flex-end',
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    speedometerDistanceUnit: {
      color: mapPanelText,
      fontSize: 9,
      fontWeight: '800',
      marginLeft: 3,
    },
    speedometerDistanceValueDecimal: {
      color: mapPanelText,
      fontFamily: NUMERIC_DISPLAY_FONT,
      fontSize: 9,
      letterSpacing: 0.2,
      lineHeight: 11,
    },
    speedometerDistanceValueDot: {
      color: mapPanelText,
      fontFamily: NUMERIC_DISPLAY_FONT,
      fontSize: 17,
      letterSpacing: 0.5,
      lineHeight: 22,
    },
    speedometerDistanceValueInteger: {
      color: mapPanelText,
      fontFamily: NUMERIC_DISPLAY_FONT,
      fontSize: 17,
      letterSpacing: 0.5,
      lineHeight: 22,
    },
    speedometerDistanceValueRow: {
      alignItems: 'flex-end',
      flexDirection: 'row',
      justifyContent: 'flex-end',
    },
    speedometerGaugeFill: {
      borderRadius: 999,
      height: 8,
    },
    speedometerGaugeTrack: {
      backgroundColor: '#070707',
      borderColor: '#000000',
      borderRadius: 999,
      borderWidth: 2,
      height: 13,
      overflow: 'hidden',
      width: 122,
    },
    speedometerLabel: {
      color: mapPanelText,
      fontSize: 11,
      fontWeight: '900',
      letterSpacing: -0.2,
    },
    speedometerPanel: {
      backgroundColor: mapPanelBackground,
      borderBottomLeftRadius: 14,
      borderBottomRightRadius: 14,
      borderTopLeftRadius: 14,
      borderTopRightRadius: 56,
      gap: 3,
      minHeight: 108,
      paddingHorizontal: 8,
      paddingVertical: 8,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.24,
      shadowRadius: 10,
      width: 160,
    },
    speedometerSpeedRow: {
      gap: 0,
    },
    speedometerSpeedUnit: {
      color: mapPanelText,
      fontSize: 9,
      fontWeight: '800',
      marginBottom: 5,
      marginLeft: 4,
    },
    speedometerSpeedValue: {
      fontFamily: NUMERIC_DISPLAY_FONT,
      fontSize: 37,
      letterSpacing: 0.5,
      lineHeight: 43,
    },
    speedometerValueRow: {
      alignItems: 'flex-end',
      flexDirection: 'row',
      justifyContent: 'flex-end',
      marginTop: -5,
      paddingRight: 16,
    },

    // Custom user location marker
    customUserLocationMarker: {
      alignItems: 'center',
      backgroundColor: colors.primary,
      borderColor: colors.card,
      borderRadius: 999,
      borderWidth: 3,
      height: 42,
      justifyContent: 'center',
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.22,
      shadowRadius: 14,
      width: 42,
    },
    customUserLocationMarkerImage: {
      borderColor: colors.card,
      borderRadius: 999,
      borderWidth: 3,
      height: 42,
      width: 42,
    },

    // Stay place marker
    stayPlaceMapMarkerBubble: {
      alignItems: 'center',
      backgroundColor: colors.card,
      borderColor: colors.border,
      borderRadius: 10,
      borderWidth: 1,
      elevation: 5,
      height: 44,
      justifyContent: 'center',
      shadowColor: '#000000',
      shadowOffset: { height: 3, width: 0 },
      shadowOpacity: 0.22,
      shadowRadius: 6,
      width: 44,
    },
    stayPlaceMapMarkerContainer: {
      alignItems: 'center',
      height: 50,
      justifyContent: 'flex-start',
      width: 44,
    },
    stayPlaceMapMarkerImage: {
      height: 28,
      width: 28,
    },
    stayPlaceMapDialogContent: {
      alignItems: 'center',
      gap: 8,
      paddingHorizontal: 26,
      paddingVertical: 18,
    },
    stayPlaceMapDialogImage: {
      height: 42,
      width: 42,
    },
    stayPlaceMapDialogPrivacy: {
      color: colors.mutedText,
      fontSize: 13,
    },
    stayPlaceMapDialogTitle: {
      color: colors.text,
      fontSize: 20,
      fontWeight: '700',
    },

    // Photo markers (map overlay)
    photoMarkerBubble: {
      backgroundColor: colors.surfaceOverlay,
      borderColor: colors.card,
      borderRadius: 10,
      borderWidth: 2,
      height: 42,
      overflow: 'hidden',
      padding: 2,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.18,
      shadowRadius: 12,
      width: 42,
    },
    photoMarkerContainer: {
      alignItems: 'center',
      height: 46,
      justifyContent: 'center',
      width: 46,
    },
    photoMarkerImage: {
      borderRadius: 7,
      height: '100%',
      width: '100%',
    },
    photoClusterBadge: {
      alignItems: 'center',
      backgroundColor: colors.primary,
      borderColor: colors.card,
      borderRadius: 999,
      borderWidth: 2,
      bottom: 1,
      minWidth: 24,
      paddingHorizontal: 5,
      paddingVertical: 2,
      position: 'absolute',
      right: 1,
    },
    photoClusterBadgeText: {
      color: colors.primaryText,
      fontSize: 11,
      fontWeight: '900',
    },
    photoClusterCallout: {
      alignSelf: 'center',
      backgroundColor: colors.cardStrong,
      borderColor: colors.border,
      borderRadius: 18,
      borderWidth: 1,
      gap: 8,
      padding: 10,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.2,
      shadowRadius: 18,
      width: 184,
    },
    photoClusterGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 6,
    },
    photoClusterGridImage: {
      borderRadius: 8,
      height: '100%',
      width: '100%',
    },
    photoClusterGridItem: {
      height: 50,
      width: 50,
    },
    photoClusterMarkerBubble: {
      backgroundColor: colors.surfaceOverlay,
      borderColor: colors.card,
      borderRadius: 16,
      borderWidth: 3,
      height: 52,
      overflow: 'hidden',
      padding: 2,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.22,
      shadowRadius: 14,
      width: 52,
    },
    photoClusterMarkerContainer: {
      alignItems: 'center',
      height: 56,
      justifyContent: 'center',
      width: 56,
    },
    photoClusterMoreText: {
      color: colors.mutedText,
      fontSize: 12,
      fontWeight: '800',
      textAlign: 'center',
    },
    photoClusterOverlay: {
      alignItems: 'center',
      backgroundColor: theme.name === 'dark' ? 'rgba(0, 0, 0, 0.34)' : 'rgba(45, 36, 22, 0.18)',
      flex: 1,
      justifyContent: 'center',
      padding: 24,
    },
    photoClusterPage: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 6,
      width: 162,
    },
    photoClusterPager: {
      width: 162,
    },
    photoClusterTitle: {
      color: colors.text,
      fontSize: 14,
      fontWeight: '900',
      textAlign: 'center',
    },
    photoPreviewBackdrop: {
      alignItems: 'center',
      backgroundColor: 'rgba(0, 0, 0, 0.92)',
      flex: 1,
      justifyContent: 'center',
    },
    photoPreviewCloseArea: {
      alignItems: 'center',
      flex: 1,
      justifyContent: 'center',
      padding: 18,
      width: '100%',
    },
    photoPreviewHint: {
      bottom: 42,
      color: '#ffffff',
      fontWeight: '800',
      position: 'absolute',
    },
    photoPreviewImage: {
      height: '88%',
      width: '100%',
    },
    photoStatusCard: {
      alignSelf: 'center',
      backgroundColor: colors.surfaceOverlay,
      borderColor: colors.border,
      borderRadius: 18,
      borderWidth: 1,
      marginHorizontal: 24,
      paddingHorizontal: 14,
      paddingVertical: 10,
    },

    // GPS permission UI
    permissionButton: {
      alignItems: 'center',
      backgroundColor: colors.danger,
      borderRadius: 999,
      paddingHorizontal: 16,
      paddingVertical: 12,
    },
    permissionButtonText: {
      color: colors.primaryText,
      fontWeight: '900',
    },
    permissionCard: {
      alignSelf: 'center',
      backgroundColor: colors.dangerSurface,
      borderColor: colors.danger,
      borderRadius: 24,
      borderWidth: 1,
      gap: 10,
      marginHorizontal: 20,
      marginTop: 92,
      padding: 16,
    },
    permissionSettingsBox: {
      backgroundColor: colors.dangerSurface,
      borderColor: colors.danger,
      borderRadius: 20,
      borderWidth: 1,
      gap: 10,
      padding: 14,
    },
    permissionText: {
      color: colors.mutedText,
      lineHeight: 20,
    },
    permissionTitle: {
      color: colors.danger,
      fontSize: 17,
      fontWeight: '900',
    },
  } as const;
}
