import { StyleSheet } from 'react-native';

import { NUMERIC_DISPLAY_FONT } from '../../../theme/fonts';

const reportBackground = '#202020';
const reportSurface = '#2d2d2d';
const reportSurfaceElevated = '#383838';
const reportText = '#ffffff';
const reportMuted = 'rgba(255,255,255,0.66)';
const reportSubtle = 'rgba(255,255,255,0.18)';
const reportAccent = '#f5a900';

/** 月次レポートのストーリーUI専用スタイル。 */
export const reportStyles = StyleSheet.create({
  achievementEmptyText: {
    color: reportMuted,
    fontSize: 19,
    fontWeight: '800',
    lineHeight: 28,
    textAlign: 'center',
  },
  achievementList: {
    gap: 14,
  },
  achievementRow: {
    alignItems: 'center',
    backgroundColor: reportSurfaceElevated,
    borderRadius: 22,
    flexDirection: 'row',
    gap: 14,
    minHeight: 82,
    paddingHorizontal: 18,
    paddingVertical: 14,
  },
  achievementText: {
    color: reportText,
    flex: 1,
    fontSize: 20,
    fontWeight: '900',
    lineHeight: 26,
  },
  achievementTrophy: {
    fontSize: 34,
  },
  card: {
    backgroundColor: reportBackground,
    flex: 1,
    overflow: 'hidden',
  },
  centerContent: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    paddingBottom: 120,
    paddingHorizontal: 24,
    paddingTop: 154,
  },
  distanceCaption: {
    color: reportMuted,
    fontSize: 18,
    fontWeight: '800',
    lineHeight: 24,
    marginTop: 22,
    textAlign: 'center',
  },
  distanceLead: {
    color: reportText,
    fontSize: 24,
    fontWeight: '900',
    lineHeight: 31,
    marginBottom: 22,
    textAlign: 'center',
  },
  distanceNumber: {
    color: reportText,
    fontFamily: NUMERIC_DISPLAY_FONT,
    fontSize: 64,
    letterSpacing: 1,
    lineHeight: 76,
    textAlign: 'right',
  },
  distanceRow: {
    alignItems: 'baseline',
    flexDirection: 'row',
    justifyContent: 'center',
    maxWidth: '100%',
  },
  distanceUnit: {
    color: reportText,
    fontSize: 34,
    fontWeight: '900',
    lineHeight: 42,
    marginLeft: 10,
  },
  distanceVerdict: {
    color: reportText,
    fontSize: 26,
    fontWeight: '900',
    lineHeight: 34,
    marginTop: 30,
    textAlign: 'center',
  },
  header: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    left: 24,
    position: 'absolute',
    right: 24,
    top: 58,
    zIndex: 5,
  },
  headerIcon: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 14,
    height: 50,
    justifyContent: 'center',
    overflow: 'hidden',
    width: 50,
  },
  headerIconImage: {
    height: 42,
    width: 42,
  },
  headerSubtitle: {
    color: reportMuted,
    fontSize: 18,
    fontWeight: '800',
    lineHeight: 23,
  },
  headerText: {
    flex: 1,
    minWidth: 0,
  },
  headerTitle: {
    color: reportText,
    fontSize: 25,
    fontWeight: '900',
    lineHeight: 31,
  },
  mapBackground: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#13212a',
  },
  mapGridLine: {
    backgroundColor: 'rgba(255,255,255,0.08)',
    height: 3,
    left: -80,
    position: 'absolute',
    right: -80,
    transform: [{ rotate: '-18deg' }],
  },
  mapOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.26)',
  },
  mapRoute: {
    backgroundColor: '#79a9d6',
    borderRadius: 999,
    height: 8,
    left: '24%',
    position: 'absolute',
    right: '18%',
    top: '54%',
    transform: [{ rotate: '-22deg' }],
  },
  mapRouteHalo: {
    backgroundColor: 'rgba(121,169,214,0.2)',
    borderRadius: 999,
    height: 22,
    left: '22%',
    position: 'absolute',
    right: '16%',
    top: '53.4%',
    transform: [{ rotate: '-22deg' }],
  },
  pageBody: {
    flex: 1,
    justifyContent: 'center',
    paddingBottom: 112,
    paddingHorizontal: 24,
    paddingTop: 154,
  },
  progressBar: {
    backgroundColor: 'rgba(255,255,255,0.28)',
    borderRadius: 999,
    flex: 1,
    height: 5,
    overflow: 'hidden',
  },
  progressFill: {
    backgroundColor: reportText,
    height: '100%',
  },
  progressRow: {
    flexDirection: 'row',
    gap: 6,
    left: 24,
    position: 'absolute',
    right: 24,
    top: 25,
    zIndex: 6,
  },
  rankingList: {
    gap: 14,
  },
  rankingName: {
    color: reportText,
    flex: 1,
    fontSize: 28,
    fontWeight: '900',
    lineHeight: 36,
  },
  rankingRank: {
    color: reportText,
    fontSize: 28,
    fontStyle: 'italic',
    fontWeight: '900',
    width: 70,
  },
  rankingRow: {
    alignItems: 'center',
    backgroundColor: reportSurface,
    borderRadius: 22,
    flexDirection: 'row',
    gap: 12,
    minHeight: 84,
    paddingHorizontal: 18,
    paddingVertical: 16,
  },
  rankingVisits: {
    color: reportMuted,
    fontSize: 20,
    fontWeight: '900',
  },
  shareButton: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 999,
    bottom: 34,
    height: 58,
    justifyContent: 'center',
    minHeight: 44,
    minWidth: 44,
    position: 'absolute',
    right: 24,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.24,
    shadowRadius: 14,
    width: 58,
    zIndex: 10,
  },
  storyContainer: {
    backgroundColor: reportBackground,
    flex: 1,
  },
  targetGauge: {
    alignSelf: 'stretch',
    marginTop: 46,
    maxWidth: 420,
    width: '100%',
  },
  targetGaugeBar: {
    backgroundColor: 'rgba(255,255,255,0.32)',
    borderRadius: 999,
    height: 16,
    overflow: 'hidden',
  },
  targetGaugeFill: {
    backgroundColor: reportAccent,
    borderRadius: 999,
    height: '100%',
  },
  targetGaugeLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  targetGaugeText: {
    color: reportText,
    fontSize: 18,
    fontWeight: '900',
  },
  targetHere: {
    color: reportMuted,
    fontSize: 15,
    fontWeight: '800',
    marginTop: 8,
    textAlign: 'center',
  },
});
