import { StyleSheet } from 'react-native';

import { NUMERIC_DISPLAY_FONT } from '../../../theme/fonts';

const reportBackground = '#202020';
const reportSurface = '#2d2d2d';
const reportSurfaceElevated = '#383838';
const reportText = '#ffffff';
const reportMuted = 'rgba(255,255,255,0.66)';
const reportSubtle = 'rgba(255,255,255,0.18)';
const reportAccent = '#f5a900';

/** 月次レポートのストーリーUI専用スタイル。 */
export const reportStyles = StyleSheet.create({
  achievementEmptyText: {
    color: reportMuted,
    fontSize: 19,
    fontWeight: '800',
    lineHeight: 28,
    textAlign: 'center',
  },
  achievementList: {
    gap: 14,
  },
  achievementRow: {
    alignItems: 'center',
    backgroundColor: reportSurfaceElevated,
    borderRadius: 22,
    flexDirection: 'row',
    gap: 14,
    minHeight: 82,
    paddingHorizontal: 18,
    paddingVertical: 14,
  },
  achievementText: {
    color: reportText,
    flex: 1,
    fontSize: 20,
    fontWeight: '900',
    lineHeight: 26,
  },
  achievementTrophy: {
    fontSize: 34,
  },
  card: {
    backgroundColor: reportBackground,
    flex: 1,
    overflow: 'hidden',
  },
  centerContent: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    paddingBottom: 120,
    paddingHorizontal: 24,
    paddingTop: 154,
  },
  distanceCaption: {
    color: reportMuted,
    fontSize: 18,
    fontWeight: '800',
    lineHeight: 24,
    marginTop: 22,
    textAlign: 'center',
  },
  distanceLead: {
    color: reportText,
    fontSize: 24,
    fontWeight: '900',
    lineHeight: 31,
    marginBottom: 22,
    textAlign: 'center',
  },
  distanceNumber: {
    color: reportText,
    fontFamily: NUMERIC_DISPLAY_FONT,
    fontSize: 64,
    letterSpacing: 1,
    lineHeight: 76,
    textAlign: 'right',
  },
  distanceRow: {
    alignItems: 'baseline',
    flexDirection: 'row',
    justifyContent: 'center',
    maxWidth: '100%',
  },
  distanceUnit: {
    color: reportText,
    fontSize: 34,
    fontWeight: '900',
    lineHeight: 42,
    marginLeft: 10,
  },
  distanceVerdict: {
    color: reportText,
    fontSize: 26,
    fontWeight: '900',
    lineHeight: 34,
    marginTop: 30,
    textAlign: 'center',
  },
  header: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    left: 24,
    position: 'absolute',
    right: 24,
    top: 58,
    zIndex: 5,
  },
  headerIcon: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 14,
    height: 50,
    justifyContent: 'center',
    overflow: 'hidden',
    width: 50,
  },
  headerIconImage: {
    height: 42,
    width: 42,
  },
  headerSubtitle: {
    color: reportMuted,
    fontSize: 18,
    fontWeight: '800',
    lineHeight: 23,
  },
  headerText: {
    flex: 1,
    minWidth: 0,
  },
  headerTitle: {
    color: reportText,
    fontSize: 25,
    fontWeight: '900',
    lineHeight: 31,
  },
  mapBackground: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#13212a',
  },
  mapGridLine: {
    backgroundColor: 'rgba(255,255,255,0.08)',
    height: 3,
    left: -80,
    position: 'absolute',
    right: -80,
    transform: [{ rotate: '-18deg' }],
  },
  mapOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.26)',
  },
  mapRoute: {
    backgroundColor: '#79a9d6',
    borderRadius: 999,
    height: 8,
    left: '24%',
    position: 'absolute',
    right: '18%',
    top: '54%',
    transform: [{ rotate: '-22deg' }],
  },
  mapRouteHalo: {
    backgroundColor: 'rgba(121,169,214,0.2)',
    borderRadius: 999,
    height: 22,
    left: '22%',
    position: 'absolute',
    right: '16%',
    top: '53.4%',
    transform: [{ rotate: '-22deg' }],
  },
  pageBody: {
    flex: 1,
    justifyContent: 'center',
    paddingBottom: 112,
    paddingHorizontal: 24,
    paddingTop: 154,
  },
  progressBar: {
    backgroundColor: 'rgba(255,255,255,0.28)',
    borderRadius: 999,
    flex: 1,
    height: 5,
    overflow: 'hidden',
  },
  progressFill: {
    backgroundColor: reportText,
    height: '100%',
  },
  progressRow: {
    flexDirection: 'row',
    gap: 6,
    left: 24,
    position: 'absolute',
    right: 24,
    top: 25,
    zIndex: 6,
  },
  rankingList: {
    gap: 14,
  },
  rankingName: {
    color: reportText,
    flex: 1,
    fontSize: 28,
    fontWeight: '900',
    lineHeight: 36,
  },
  rankingRank: {
    color: reportText,
    fontSize: 28,
    fontStyle: 'italic',
    fontWeight: '900',
    width: 70,
  },
  rankingRow: {
    alignItems: 'center',
    backgroundColor: reportSurface,
    borderRadius: 22,
    flexDirection: 'row',
    gap: 12,
    minHeight: 84,
    paddingHorizontal: 18,
    paddingVertical: 16,
  },
  rankingVisits: {
    color: reportMuted,
    fontSize: 20,
    fontWeight: '900',
  },
  shareButton: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 999,
    bottom: 34,
    height: 58,
    justifyContent: 'center',
    minHeight: 44,
    minWidth: 44,
    position: 'absolute',
    right: 24,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.24,
    shadowRadius: 14,
    width: 58,
    zIndex: 10,
  },
  storyContainer: {
    backgroundColor: reportBackground,
    flex: 1,
  },
  targetGauge: {
    alignSelf: 'stretch',
    marginTop: 46,
    maxWidth: 420,
    width: '100%',
  },
  targetGaugeBar: {
    backgroundColor: 'rgba(255,255,255,0.32)',
    borderRadius: 999,
    height: 16,
    overflow: 'hidden',
  },
  targetGaugeFill: {
    backgroundColor: reportAccent,
    borderRadius: 999,
    height: '100%',
  },
  targetGaugeLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  targetGaugeText: {
    color: reportText,
    fontSize: 18,
    fontWeight: '900',
  },
  targetHere: {
    color: reportMuted,
    fontSize: 15,
    fontWeight: '800',
    marginTop: 8,
    textAlign: 'center',
  },
  monthlyAchievementImage: {
    height: 74,
    width: 74,
  },
  monthlyAchievementItem: {
    alignItems: 'center',
    gap: 8,
    width: 92,
  },
  monthlyAchievementList: {
    gap: 12,
    paddingRight: 22,
  },
  monthlyAchievementTitle: {
    fontSize: 11,
    fontWeight: '800',
    lineHeight: 14,
    maxWidth: 92,
    textAlign: 'center',
  },
  monthlyAchievementsCard: {
    alignItems: 'stretch',
    borderRadius: 0,
    minHeight: 104,
    paddingHorizontal: 0,
    paddingVertical: 0,
  },
  monthlyAnimatedCard: {
    alignItems: 'center',
    borderRadius: 28,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 26,
    marginTop: 14,
    minHeight: 74,
    paddingHorizontal: 22,
    paddingVertical: 14,
  },
  monthlyAppName: {
    fontSize: 36,
    fontWeight: '900',
    letterSpacing: -1,
    lineHeight: 43,
  },
  monthlyCardLabel: {
    fontSize: 16,
    fontWeight: '800',
    lineHeight: 22,
  },
  monthlyCardNumberDecimal: {
    fontFamily: NUMERIC_DISPLAY_FONT,
    fontSize: 21,
    letterSpacing: -0.5,
    lineHeight: 30,
  },
  monthlyCardNumberInteger: {
    fontFamily: NUMERIC_DISPLAY_FONT,
    fontSize: 33,
    letterSpacing: -0.5,
    lineHeight: 42,
  },
  monthlyCardSubLabel: {
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
    marginTop: 2,
  },
  monthlyCardUnit: {
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 20,
    marginLeft: 5,
  },
  monthlyBottomSafeArea: {
    alignSelf: 'stretch',
  },
  monthlyBottomSpacer: {
    height: 56,
  },
  monthlyCaptureContent: {
    paddingBottom: 0,
  },
  monthlyContainer: {
    flex: 1,
  },
  monthlyContent: {
    paddingBottom: 0,
  },
  monthlyCloseButton: {
    alignItems: 'center',
    alignSelf: 'flex-end',
    backgroundColor: '#ffffff',
    borderRadius: 999,
    height: 48,
    justifyContent: 'center',
    marginRight: 20,
    marginTop: 12,
    minHeight: 44,
    minWidth: 44,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.18,
    shadowRadius: 12,
    width: 48,
  },
  monthlyCloseSafeArea: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 11,
  },
  monthlyEmptyText: {
    fontSize: 16,
    fontWeight: '800',
    lineHeight: 22,
    paddingHorizontal: 24,
  },
  monthlyInlineShareButton: {
    marginHorizontal: 26,
    marginTop: 72,
  },
  monthlyInlineShareText: {
  },
  monthlyReportEndSpacer: {
    height: 24,
  },
  monthlyShareBranding: {
    marginBottom: 24,
    marginRight: 24,
  },
  monthlyHero: {
    alignItems: 'center',
    minHeight: 328,
    paddingHorizontal: 28,
    paddingTop: 0,
  },
  monthlyIcon: {
    height: 60,
    width: 60,
  },
  monthlyIconFrame: {
    alignItems: 'center',
    borderRadius: 18,
    height: 72,
    justifyContent: 'center',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.22,
    shadowRadius: 5,
    width: 72,
  },
  monthlyMapCard: {
    alignItems: 'stretch',
    borderRadius: 28,
    flexDirection: 'column',
    height: 220,
    justifyContent: 'center',
    overflow: 'hidden',
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  monthlyMapGridLine: {
    backgroundColor: 'rgba(255,255,255,0.08)',
    height: 2,
    left: -40,
    position: 'absolute',
    right: -40,
    transform: [{ rotate: '-18deg' }],
  },
  monthlyMapPreview: {
    backgroundColor: '#14222a',
    borderRadius: 22,
    flex: 1,
    overflow: 'hidden',
    width: '100%',
  },
  monthlyMapNoData: {
    alignItems: 'center',
    backgroundColor: '#14222a',
    borderRadius: 22,
    flex: 1,
    height: '100%',
    justifyContent: 'center',
    width: '100%',
  },
  monthlyMapRoute: {
    backgroundColor: '#4f87bd',
    borderRadius: 999,
    height: 7,
    left: '26%',
    position: 'absolute',
    right: '15%',
    top: '48%',
    transform: [{ rotate: '-20deg' }],
  },
  monthlyMapRouteHalo: {
    backgroundColor: 'rgba(79,135,189,0.24)',
    borderRadius: 999,
    height: 18,
    left: '24%',
    position: 'absolute',
    right: '13%',
    top: '46%',
    transform: [{ rotate: '-20deg' }],
  },
  monthlyMapView: {
    borderRadius: 22,
    flex: 1,
    overflow: 'hidden',
    width: '100%',
  },
  monthlyMetricRow: {
    alignItems: 'center',
    alignSelf: 'stretch',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  monthlyMetricValueRow: {
    alignItems: 'flex-end',
    flexDirection: 'row',
    flexShrink: 0,
    justifyContent: 'flex-end',
  },
  monthlyNoDataText: {
    fontSize: 18,
    fontWeight: '800',
    lineHeight: 24,
    textAlign: 'right',
  },
  monthlyPlaceText: {
    flex: 1,
    fontSize: 22,
    fontWeight: '800',
    lineHeight: 29,
    textAlign: 'right',
  },
  monthlyRankText: {
    fontSize: 18,
    fontWeight: '700',
    lineHeight: 24,
    width: 52,
  },
  monthlyRankingDays: {
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 20,
  },
  monthlyRankingName: {
    flex: 1,
    fontSize: 24,
    fontWeight: '800',
    lineHeight: 31,
    textAlign: 'right',
  },
  monthlyScrollChevron: {
    borderBottomWidth: 2,
    borderRightWidth: 2,
    height: 42,
    marginTop: -8,
    transform: [{ rotate: '45deg' }],
    width: 42,
  },
  monthlyScrollIndicator: {
    alignItems: 'center',
    marginTop: 48,
  },
  monthlyScrollText: {
    fontSize: 18,
    fontWeight: '500',
    letterSpacing: 0.4,
    lineHeight: 24,
  },
  monthlySectionTitle: {
    fontSize: 16,
    fontWeight: '800',
    lineHeight: 22,
    marginHorizontal: 26,
    marginTop: 24,
  },
  monthlyStackCard: {
    alignItems: 'stretch',
    flexDirection: 'column',
    gap: 10,
    justifyContent: 'center',
  },
  monthlyTopSafeArea: {
    alignSelf: 'stretch',
  },
  monthlyTopSpacer: {
    height: 64,
  },
  monthlySubtitle: {
    fontSize: 20,
    fontWeight: '500',
    lineHeight: 26,
  },
  monthlyTitleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 14,
    justifyContent: 'center',
    marginTop: 8,
  },
  monthlyTitleTextBlock: {
    minWidth: 0,
  },
  newRecordPill: {
    alignItems: 'center',
    alignSelf: 'stretch',
    backgroundColor: '#ff3c86',
    borderColor: '#ffffff',
    borderRadius: 999,
    borderWidth: 4,
    justifyContent: 'center',
    minHeight: 28,
  },
  newRecordText: {
    color: '#ffffff',
    fontSize: 15,
    fontStyle: 'italic',
    fontWeight: '900',
    letterSpacing: 4,
    lineHeight: 19,
  },
});
