import { StyleSheet } from 'react-native';

import { NUMERIC_DISPLAY_FONT } from '../../../theme/fonts';

/** 月次レポートのストーリーUI専用スタイル。 */
export const reportStyles = StyleSheet.create({
  achievementEmptyText: {
    color: 'rgba(255,255,255,0.68)',
    fontSize: 22,
    fontWeight: '900',
    lineHeight: 30,
    textAlign: 'center',
  },
  achievementRow: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderRadius: 24,
    flexDirection: 'row',
    gap: 14,
    padding: 14,
  },
  achievementText: {
    color: '#ffffff',
    flex: 1,
    fontSize: 18,
    fontWeight: '900',
  },
  achievementTrophy: {
    fontSize: 36,
  },
  card: {
    backgroundColor: '#242424',
    flex: 1,
    overflow: 'hidden',
  },
  centerContent: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 28,
  },
  distanceLead: {
    color: '#ffffff',
    fontSize: 34,
    fontWeight: '900',
    marginBottom: 44,
  },
  distanceNumber: {
    color: '#ffffff',
    fontFamily: NUMERIC_DISPLAY_FONT,
    fontSize: 76,
    letterSpacing: 2,
    lineHeight: 92,
  },
  distanceRow: {
    alignItems: 'baseline',
    flexDirection: 'row',
    gap: 12,
  },
  distanceUnit: {
    color: '#ffffff',
    fontSize: 40,
    fontWeight: '900',
  },
  distanceVerdict: {
    color: '#ffffff',
    fontSize: 34,
    fontWeight: '900',
    marginTop: 48,
  },
  header: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    left: 28,
    position: 'absolute',
    right: 28,
    top: 92,
    zIndex: 5,
  },
  headerIcon: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 14,
    height: 58,
    justifyContent: 'center',
    width: 58,
  },
  headerIconText: {
    fontSize: 30,
  },
  headerSubtitle: {
    color: 'rgba(255,255,255,0.58)',
    fontSize: 22,
    fontWeight: '900',
  },
  headerText: {
    flex: 1,
  },
  headerTitle: {
    color: '#ffffff',
    fontSize: 27,
    fontWeight: '900',
    lineHeight: 32,
  },
  mapBackground: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#1d3240',
  },
  mapGridLine: {
    backgroundColor: 'rgba(255,255,255,0.16)',
    height: 4,
    left: -40,
    position: 'absolute',
    right: -40,
    transform: [{ rotate: '-18deg' }],
  },
  mapOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.38)',
  },
  mapRoute: {
    backgroundColor: '#70a8dc',
    borderRadius: 999,
    height: 8,
    left: 120,
    position: 'absolute',
    right: 80,
    top: '48%',
    transform: [{ rotate: '-22deg' }],
  },
  pageBody: {
    flex: 1,
    paddingBottom: 120,
    paddingHorizontal: 28,
    paddingTop: 230,
  },
  progressBar: {
    backgroundColor: 'rgba(255,255,255,0.46)',
    borderRadius: 999,
    flex: 1,
    height: 8,
    overflow: 'hidden',
  },
  progressFill: {
    backgroundColor: '#ffffff',
    height: '100%',
  },
  progressRow: {
    flexDirection: 'row',
    gap: 5,
    left: 28,
    position: 'absolute',
    right: 28,
    top: 64,
    zIndex: 6,
  },
  rankingList: {
    gap: 38,
    marginTop: 120,
  },
  rankingName: {
    color: '#ffffff',
    flex: 1,
    fontSize: 44,
    fontWeight: '900',
  },
  rankingRank: {
    color: '#ffffff',
    fontSize: 50,
    fontStyle: 'italic',
    fontWeight: '900',
    width: 130,
  },
  rankingRow: {
    alignItems: 'center',
    backgroundColor: '#303030',
    flexDirection: 'row',
    gap: 18,
    marginHorizontal: -28,
    paddingHorizontal: 76,
    paddingVertical: 24,
  },
  rankingVisits: {
    color: 'rgba(255,255,255,0.62)',
    fontSize: 28,
    fontStyle: 'italic',
    fontWeight: '900',
  },
  shareButton: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 999,
    bottom: 76,
    height: 64,
    justifyContent: 'center',
    position: 'absolute',
    right: 28,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.28,
    shadowRadius: 14,
    width: 64,
    zIndex: 10,
  },
  storyContainer: {
    backgroundColor: '#000000',
    flex: 1,
  },
  targetGauge: {
    bottom: 210,
    left: 80,
    position: 'absolute',
    right: 80,
  },
  targetGaugeBar: {
    backgroundColor: '#9d9d9d',
    borderRadius: 0,
    height: 42,
    overflow: 'hidden',
  },
  targetGaugeFill: {
    backgroundColor: '#ffb000',
    height: '100%',
  },
  targetGaugeLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  targetGaugeText: {
    color: '#ffffff',
    fontSize: 38,
    fontWeight: '900',
  },
  targetHere: {
    color: '#ffffff',
    fontSize: 24,
    fontWeight: '900',
    marginTop: 10,
    textAlign: 'center',
  },
});
