import { StyleSheet } from 'react-native';

import { NUMERIC_DISPLAY_FONT } from '../theme/fonts';
import { AppTheme } from '../theme/theme';

/**
 * 現在のテーマから画面全体のStyleSheetを生成する。
 *
 * @param theme - OSカラースキームから選ばれたアプリテーマ。
 * @returns Appコンポーネントと子コンポーネントで共有するStyleSheet。
 */
export function createStyles(theme: AppTheme) {
  const { colors } = theme;
  const mapPanelBackground = theme.name === 'dark' ? 'rgba(34, 38, 29, 0.88)' : 'rgba(45, 36, 22, 0.80)';
  const mapPanelText = theme.name === 'dark' ? colors.text : colors.primaryText;

  return StyleSheet.create({

    achievementCard: {
      backgroundColor: colors.card,
      borderColor: colors.border,
      borderRadius: 20,
      borderWidth: 1,
      flexBasis: '48%',
      gap: 8,
      padding: 12,
    },
    achievementCardLocked: {
      opacity: 0.62,
    },
    achievementDescription: {
      color: colors.mutedText,
      fontSize: 12,
      fontWeight: '700',
      lineHeight: 17,
    },
    achievementGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
    },
    achievementCloseButton: {
      alignItems: 'center',
      backgroundColor: colors.card,
      borderColor: colors.border,
      borderRadius: 999,
      borderWidth: 1,
      height: 32,
      justifyContent: 'center',
      position: 'absolute',
      right: 12,
      top: 22,
      width: 32,
      zIndex: 3,
    },
    achievementCloseButtonIcon: {
      color: colors.text,
    },
    achievementImage: {
      height: 78,
      width: 78,
    },
    achievementImageFrame: {
      alignItems: 'center',
      alignSelf: 'center',
      backgroundColor: colors.cardStrong,
      borderColor: colors.border,
      borderRadius: 24,
      borderWidth: 1,
      height: 96,
      justifyContent: 'center',
      width: 96,
    },
    achievementImageLocked: {
      opacity: 0.34,
    },
    achievementLockBadge: {
      alignItems: 'center',
      backgroundColor: colors.primary,
      borderColor: colors.card,
      borderRadius: 999,
      borderWidth: 2,
      bottom: 6,
      height: 28,
      justifyContent: 'center',
      position: 'absolute',
      right: 6,
      width: 28,
    },
    achievementAutoCloseProgress: {
      backgroundColor: colors.primary,
      height: '100%',
      transformOrigin: 'left',
      width: '100%',
    },
    achievementAutoCloseTrack: {
      backgroundColor: colors.border,
      borderRadius: 999,
      height: 4,
      left: 18,
      opacity: 0.75,
      overflow: 'hidden',
      position: 'absolute',
      right: 18,
      top: 12,
    },
    achievementModalActions: {
      alignSelf: 'stretch',
      gap: 10,
    },
    achievementModalBackdrop: {
      alignItems: 'center',
      backgroundColor: theme.name === 'dark' ? 'rgba(0, 0, 0, 0.72)' : 'rgba(45, 36, 22, 0.38)',
      flex: 1,
      justifyContent: 'center',
      padding: 24,
    },
    achievementModalCard: {
      alignItems: 'center',
      backgroundColor: colors.cardStrong,
      borderColor: colors.border,
      borderRadius: 30,
      borderWidth: 1,
      gap: 12,
      maxWidth: 360,
      padding: 22,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 24 },
      shadowOpacity: 0.26,
      shadowRadius: 32,
      width: '100%',
      zIndex: 2,
    },
    achievementModalDescription: {
      color: colors.mutedText,
      fontWeight: '800',
      lineHeight: 20,
      textAlign: 'center',
    },
    achievementModalEyebrow: {
      color: colors.primary,
      fontSize: 14,
      fontWeight: '900',
      letterSpacing: 1,
    },
    achievementModalImage: {
      height: 140,
      width: 140,
    },
    achievementModalTitle: {
      color: colors.text,
      fontSize: 22,
      fontWeight: '900',
      lineHeight: 28,
      textAlign: 'center',
    },
    achievementPrimaryButton: {
      alignItems: 'center',
      backgroundColor: colors.primary,
      borderRadius: 999,
      flexDirection: 'row',
      gap: 8,
      justifyContent: 'center',
      paddingHorizontal: 18,
      paddingVertical: 14,
    },
    achievementProgress: {
      color: colors.primary,
      fontSize: 12,
      fontWeight: '900',
    },
    achievementSecondaryButton: {
      alignItems: 'center',
      backgroundColor: colors.card,
      borderColor: colors.primary,
      borderRadius: 999,
      borderWidth: 1,
      paddingHorizontal: 18,
      paddingVertical: 14,
    },
    achievementSection: {
      gap: 12,
    },
    achievementSwipeHint: {
      color: colors.mutedText,
      fontSize: 12,
      fontWeight: '900',
      textAlign: 'center',
    },
    achievementTitle: {
      color: colors.text,
      fontSize: 15,
      fontWeight: '900',
      lineHeight: 19,
    },
    actions: {
      flexDirection: 'row',
      gap: 10,
    },
    autoRecordNote: {
      color: colors.mutedText,
      fontSize: 13,
      fontWeight: '700',
      lineHeight: 18,
    },
    backButton: {
      backgroundColor: colors.card,
      borderColor: colors.border,
      borderRadius: 999,
      borderWidth: 1,
      paddingHorizontal: 14,
      paddingVertical: 10,
    },
    backButtonText: {
      color: colors.primary,
      fontWeight: '900',
    },
    bottomBar: {
      alignItems: 'center',
      bottom: 26,
      flexDirection: 'row',
      gap: 12,
      justifyContent: 'space-between',
      left: 16,
      position: 'absolute',
      right: 16,
      zIndex: 2,
    },
    bottomSideSpacer: {
      width: 50,
    },
    buttonDisabled: {
      opacity: 0.38,
    },
    confettiLayer: {
      ...StyleSheet.absoluteFillObject,
      overflow: 'hidden',
      zIndex: 1,
    },
    confettiPiece: {
      borderRadius: 1,
      height: 13,
      position: 'absolute',
      width: 9,
    },
    container: {
      backgroundColor: colors.background,
      flex: 1,
    },
    customUserLocationMarker: {
      alignItems: 'center',
      backgroundColor: colors.primary,
      borderColor: colors.card,
      borderRadius: 999,
      borderWidth: 3,
      height: 42,
      justifyContent: 'center',
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.22,
      shadowRadius: 14,
      width: 42,
    },
    customizationOption: {
      backgroundColor: colors.cardStrong,
      borderColor: colors.border,
      borderRadius: 18,
      borderWidth: 1,
      flex: 1,
      gap: 8,
      minWidth: 96,
      padding: 12,
    },
    customizationOptionGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
    },
    customizationOptionSelected: {
      borderColor: colors.primary,
      borderWidth: 2,
    },
    customizationOptionText: {
      color: colors.text,
      fontWeight: '900',
    },
    customizationSection: {
      gap: 10,
    },
    dangerAction: {
      alignItems: 'center',
      backgroundColor: colors.dangerSurface,
      borderColor: colors.danger,
      borderRadius: 18,
      borderWidth: 1,
      flexDirection: 'row',
      gap: 10,
      paddingHorizontal: 16,
      paddingVertical: 14,
    },
    dangerActionText: {
      color: colors.danger,
      fontWeight: '900',
    },
    developmentFlagBannerContainer: {
      alignItems: 'center',
      left: 0,
      position: 'absolute',
      right: 0,
      top: 0,
      zIndex: 20,
    },
    developmentFlagBannerText: {
      backgroundColor: colors.danger,
      borderBottomLeftRadius: 12,
      borderBottomRightRadius: 12,
      color: colors.primaryText,
      fontSize: 12,
      fontWeight: '900',
      overflow: 'hidden',
      paddingHorizontal: 12,
      paddingVertical: 5,
    },
    dailyCard: {
      backgroundColor: colors.card,
      borderColor: colors.border,
      borderRadius: 24,
      borderWidth: 1,
      gap: 10,
      padding: 16,
    },
    dailyContainer: {
      backgroundColor: colors.background,
      flex: 1,
    },
    dailyDate: {
      color: colors.text,
      fontSize: 22,
      fontWeight: '900',
    },
    dailyEmptyCard: {
      backgroundColor: colors.card,
      borderRadius: 24,
      gap: 8,
      margin: 16,
      padding: 18,
    },
    dailyHeader: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 12,
      justifyContent: 'space-between',
      padding: 16,
    },
    dailyList: {
      gap: 12,
      padding: 16,
      paddingTop: 0,
    },
    dailyMap: {
      height: 180,
      width: '100%',
    },
    dailyMapFrame: {
      borderRadius: 20,
      marginTop: 4,
      overflow: 'hidden',
    },
    dailyStat: {
      color: colors.text,
      fontWeight: '800',
    },
    dailyStatsRow: {
      flexDirection: 'row',
      gap: 16,
    },
    dailyTime: {
      color: colors.mutedText,
      fontWeight: '700',
    },
    dailyTitle: {
      color: colors.text,
      flex: 1,
      fontSize: 20,
      fontWeight: '900',
      textAlign: 'center',
    },
    endpointMarker: {
      borderColor: colors.card,
      borderRadius: 999,
      borderWidth: 2,
      paddingHorizontal: 10,
      paddingVertical: 6,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 8,
    },
    endpointMarkerText: {
      color: colors.primaryText,
      fontSize: 12,
      fontWeight: '900',
    },
    emptyCard: {
      alignSelf: 'center',
      backgroundColor: colors.surfaceOverlay,
      borderRadius: 24,
      gap: 6,
      marginHorizontal: 24,
      marginTop: 92,
      padding: 18,
    },
    emptyText: {
      color: colors.mutedText,
      lineHeight: 20,
    },
    emptyTitle: {
      color: colors.text,
      fontSize: 18,
      fontWeight: '800',
    },
    iconButton: {
      backgroundColor: colors.surfaceOverlay,
      borderRadius: 999,
      paddingHorizontal: 14,
      paddingVertical: 10,
    },
    iconButtonText: {
      color: colors.text,
      fontWeight: '800',
    },
    headerSpacer: {
      width: 70,
    },
    locationMetaLabel: {
      color: colors.mutedText,
      fontSize: 12,
      fontWeight: '800',
    },
    locationMetaRow: {
      alignItems: 'baseline',
      flexDirection: 'row',
      gap: 3,
    },
    locationMetaValue: {
      color: colors.mutedText,
      fontFamily: NUMERIC_DISPLAY_FONT,
      fontSize: 14,
      letterSpacing: 1,
    },
    locationName: {
      color: colors.text,
      fontSize: 15,
      fontWeight: '900',
    },
    locationPill: {
      alignItems: 'center',
      backgroundColor: colors.surfaceOverlay,
      borderColor: colors.border,
      borderRadius: 999,
      borderWidth: 1,
      gap: 2,
      flex: 1,
      maxWidth: 260,
      paddingHorizontal: 18,
      paddingVertical: 10,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.12,
      shadowRadius: 18,
    },
    loadingContainer: {
      alignItems: 'center',
      backgroundColor: colors.background,
      flex: 1,
      justifyContent: 'center',
    },
    loadingText: {
      color: colors.text,
      marginTop: 12,
    },
    map: {
      ...StyleSheet.absoluteFillObject,
    },
    menuButton: {
      alignItems: 'center',
      backgroundColor: colors.surfaceOverlay,
      borderRadius: 999,
      height: 42,
      justifyContent: 'center',
      width: 42,
    },

    menuCard: {
      backgroundColor: colors.cardStrong,
      borderColor: colors.border,
      borderRadius: 26,
      borderWidth: 1,
      overflow: 'hidden',
      position: 'absolute',
      right: 16,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 18 },
      shadowOpacity: 0.2,
      shadowRadius: 28,
      top: 70,
      width: 248,
      zIndex: 3,
    },
    menuScrim: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: theme.name === 'dark' ? 'rgba(0, 0, 0, 0.5)' : 'rgba(45, 36, 22, 0.24)',
      zIndex: 1,
    },
    menuScrimPressable: {
      flex: 1,
    },
    menuItem: {
      alignItems: 'center',
      borderBottomColor: colors.border,
      borderBottomWidth: 1,
      flexDirection: 'row',
      gap: 14,
      paddingHorizontal: 20,
      paddingVertical: 18,
    },
    menuItemText: {
      color: colors.text,
      fontSize: 17,
      fontWeight: '900',
    },
    message: {
      color: colors.mutedText,
      lineHeight: 20,
    },
    overlay: {
      ...StyleSheet.absoluteFillObject,
    },

    photoMarkerContainer: {
      alignItems: 'center',
      height: 46,
      justifyContent: 'center',
      width: 46,
    },
    photoMarkerBubble: {
      backgroundColor: colors.surfaceOverlay,
      borderColor: colors.card,
      borderRadius: 10,
      borderWidth: 2,
      height: 42,
      overflow: 'hidden',
      padding: 2,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.18,
      shadowRadius: 12,
      width: 42,
    },
    photoMarkerImage: {
      borderRadius: 7,
      height: '100%',
      width: '100%',
    },
    photoClusterBadge: {
      alignItems: 'center',
      backgroundColor: colors.primary,
      borderColor: colors.card,
      borderRadius: 999,
      borderWidth: 2,
      bottom: 1,
      minWidth: 24,
      paddingHorizontal: 5,
      paddingVertical: 2,
      position: 'absolute',
      right: 1,
    },
    photoClusterBadgeText: {
      color: colors.primaryText,
      fontSize: 11,
      fontWeight: '900',
    },
    photoClusterMarkerContainer: {
      alignItems: 'center',
      height: 56,
      justifyContent: 'center',
      width: 56,
    },
    photoClusterMarkerBubble: {
      backgroundColor: colors.surfaceOverlay,
      borderColor: colors.card,
      borderRadius: 16,
      borderWidth: 3,
      height: 52,
      overflow: 'hidden',
      padding: 2,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.22,
      shadowRadius: 14,
      width: 52,
    },
    photoClusterCallout: {
      alignSelf: 'center',
      backgroundColor: colors.cardStrong,
      borderColor: colors.border,
      borderRadius: 18,
      borderWidth: 1,
      gap: 8,
      padding: 10,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.2,
      shadowRadius: 18,
      width: 184,
    },
    photoClusterGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 6,
    },
    photoClusterGridImage: {
      borderRadius: 8,
      height: '100%',
      width: '100%',
    },
    photoClusterGridItem: {
      height: 50,
      width: 50,
    },
    photoClusterMoreText: {
      color: colors.mutedText,
      fontSize: 12,
      fontWeight: '800',
      textAlign: 'center',
    },
    photoClusterPage: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 6,
      width: 162,
    },
    photoClusterPager: {
      width: 162,
    },
    photoClusterOverlay: {
      alignItems: 'center',
      backgroundColor: theme.name === 'dark' ? 'rgba(0, 0, 0, 0.34)' : 'rgba(45, 36, 22, 0.18)',
      flex: 1,
      justifyContent: 'center',
      padding: 24,
    },
    photoClusterTitle: {
      color: colors.text,
      fontSize: 14,
      fontWeight: '900',
      textAlign: 'center',
    },
    photoPreviewBackdrop: {
      alignItems: 'center',
      backgroundColor: 'rgba(0, 0, 0, 0.92)',
      flex: 1,
      justifyContent: 'center',
    },
    photoPreviewCloseArea: {
      alignItems: 'center',
      flex: 1,
      justifyContent: 'center',
      padding: 18,
      width: '100%',
    },
    photoPreviewHint: {
      bottom: 42,
      color: '#ffffff',
      fontWeight: '800',
      position: 'absolute',
    },
    photoPreviewImage: {
      height: '88%',
      width: '100%',
    },
    photoStatusCard: {
      alignSelf: 'center',
      backgroundColor: colors.surfaceOverlay,
      borderColor: colors.border,
      borderRadius: 18,
      borderWidth: 1,
      marginHorizontal: 24,
      paddingHorizontal: 14,
      paddingVertical: 10,
    },
    permissionButton: {
      alignItems: 'center',
      backgroundColor: colors.danger,
      borderRadius: 999,
      paddingHorizontal: 16,
      paddingVertical: 12,
    },
    permissionButtonText: {
      color: colors.primaryText,
      fontWeight: '900',
    },
    permissionCard: {
      alignSelf: 'center',
      backgroundColor: colors.dangerSurface,
      borderColor: colors.danger,
      borderRadius: 24,
      borderWidth: 1,
      gap: 10,
      marginHorizontal: 20,
      marginTop: 92,
      padding: 16,
    },
    permissionSettingsBox: {
      backgroundColor: colors.dangerSurface,
      borderColor: colors.danger,
      borderRadius: 20,
      borderWidth: 1,
      gap: 10,
      padding: 14,
    },
    permissionText: {
      color: colors.mutedText,
      lineHeight: 20,
    },
    permissionTitle: {
      color: colors.danger,
      fontSize: 17,
      fontWeight: '900',
    },
    primaryButton: {
      alignItems: 'center',
      backgroundColor: colors.primary,
      borderRadius: 999,
      flex: 1,
      paddingHorizontal: 18,
      paddingVertical: 14,
    },
    primaryButtonText: {
      color: colors.primaryText,
      fontWeight: '900',
    },
    premiumBadge: {
      backgroundColor: colors.primary,
      borderRadius: 999,
      color: colors.primaryText,
      fontSize: 11,
      fontWeight: '900',
      overflow: 'hidden',
      paddingHorizontal: 8,
      paddingVertical: 4,
    },

    reportNavigationOverlay: {
      ...StyleSheet.absoluteFillObject,
      flexDirection: 'row',
      zIndex: 8,
    },
    reportNextZone: {
      flex: 1,
    },
    reportPreviousZone: {
      flex: 1,
    },
    screenTransition: {
      flex: 1,
    },
    secondaryButton: {
      alignItems: 'center',
      backgroundColor: colors.card,
      borderColor: colors.primary,
      borderRadius: 999,
      borderWidth: 1,
      minWidth: 92,
      paddingHorizontal: 16,
      paddingVertical: 14,
    },
    secondaryButtonText: {
      color: colors.primary,
      fontWeight: '900',
    },
    recenterButton: {
      alignItems: 'center',
      backgroundColor: mapPanelBackground,
      borderRadius: 14,
      gap: 5,
      height: 88,
      justifyContent: 'center',
      paddingHorizontal: 20,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.24,
      shadowRadius: 10,
      width: 132,
    },
    recenterButtonContainer: {
      alignItems: 'flex-end',
      width: 132,
    },
    recenterButtonText: {
      color: mapPanelText,
      fontSize: 13,
      fontWeight: '900',
    },
    rightControls: {
      flexDirection: 'row',
      gap: 10,
    },
    routeLinePreview: {
      borderRadius: 999,
      width: 56,
    },
    routeLinePreviewGlow: {
      borderRadius: 999,
      height: 14,
      opacity: 0.28,
      position: 'absolute',
      width: 64,
    },
    routeLinePreviewRow: {
      alignItems: 'center',
      height: 18,
      justifyContent: 'center',
    },
    speedometerDistanceRow: {
      alignItems: 'flex-end',
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    speedometerDistanceUnit: {
      color: mapPanelText,
      fontSize: 9,
      fontWeight: '800',
      marginLeft: 3,
    },
    speedometerDistanceValue: {
      color: mapPanelText,
      fontFamily: NUMERIC_DISPLAY_FONT,
      fontSize: 17,
      letterSpacing: 0.5,
      lineHeight: 22,
    },
    speedometerDistanceValueRow: {
      alignItems: 'flex-end',
      flexDirection: 'row',
    },
    speedometerGaugeFill: {
      borderRadius: 999,
      height: 8,
    },
    speedometerGaugeTrack: {
      backgroundColor: '#070707',
      borderColor: '#000000',
      borderRadius: 999,
      borderWidth: 2,
      height: 13,
      overflow: 'hidden',
      width: 122,
    },
    speedometerLabel: {
      color: mapPanelText,
      fontSize: 12,
      fontWeight: '900',
      letterSpacing: -0.2,
    },
    speedometerPanel: {
      backgroundColor: mapPanelBackground,
      borderBottomLeftRadius: 14,
      borderBottomRightRadius: 14,
      borderTopLeftRadius: 14,
      borderTopRightRadius: 56,
      gap: 3,
      minHeight: 108,
      paddingHorizontal: 8,
      paddingVertical: 8,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.24,
      shadowRadius: 10,
      width: 160,
    },
    speedometerSpeedRow: {
      gap: 0,
    },
    speedometerSpeedUnit: {
      color: mapPanelText,
      fontSize: 9,
      fontWeight: '800',
      marginBottom: 5,
      marginLeft: 4,
    },
    speedometerSpeedValue: {
      fontFamily: NUMERIC_DISPLAY_FONT,
      fontSize: 37,
      letterSpacing: 0.5,
      lineHeight: 43,
    },
    speedometerValueRow: {
      alignItems: 'flex-end',
      flexDirection: 'row',
      justifyContent: 'flex-end',
      marginTop: -5,
      paddingRight: 16,
    },
    settingsAction: {
      alignItems: 'center',
      backgroundColor: colors.cardStrong,
      borderRadius: 18,
      flexDirection: 'row',
      gap: 10,
      paddingHorizontal: 16,
      paddingVertical: 14,
    },
    settingsActionText: {
      color: colors.primary,
      fontWeight: '900',
    },
    settingsActionTextColumn: {
      flex: 1,
      gap: 5,
    },
    settingsActionTitleRow: {
      alignItems: 'center',
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    settingsCard: {
      backgroundColor: colors.card,
      borderColor: colors.border,
      borderRadius: 24,
      borderWidth: 1,
      gap: 14,
      padding: 16,
    },
    settingsDescription: {
      color: colors.mutedText,
      lineHeight: 20,
    },
    settingsList: {
      gap: 12,
      padding: 16,
      paddingTop: 0,
    },
    settingsStatusRow: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 8,
    },
    settingsStatusText: {
      color: colors.text,
      fontWeight: '900',
    },
    settingsTitle: {
      color: colors.text,
      fontSize: 20,
      fontWeight: '900',
    },
    settingsToggleRow: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 14,
    },
    settingsToggleTextColumn: {
      flex: 1,
      gap: 8,
    },
    stat: {
      color: colors.text,
      fontWeight: '800',
    },
    statsRow: {
      flexDirection: 'row',
      gap: 16,
    },
    statusDot: {
      backgroundColor: colors.border,
      borderRadius: 999,
      height: 9,
      width: 9,
    },
    statusDotActive: {
      backgroundColor: colors.primary,
    },
    statusPill: {
      alignItems: 'center',
      backgroundColor: colors.surfaceOverlay,
      borderRadius: 999,
      flexDirection: 'row',
      gap: 8,
      paddingHorizontal: 14,
      paddingVertical: 10,
    },
    statusText: {
      color: colors.text,
      fontWeight: '900',
    },
    topBar: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingTop: 8,
      zIndex: 2,
    },
  });
}

/** App画面群で共有するStyleSheetの型。 */
export type AppStyles = ReturnType<typeof createStyles>;
